version: "3"

services:

  djangoapp:
    build: ./djangoapp
    ports:
      - "5000:5000"
    volumes:
      - ./djangoapp:/djangoapp

  flaskapp:
    build: ./flaskapp
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
    restart: always