version: "3"

services:

  djangoapp:
    build: ./djangoapp
    ports:
      - "5000:5000"
    volumes:
      - ./djangoapp:/djangoapp
    environment:
      - ALLOWED_HOSTS_PUSH=djangoapp

  #flaskapp:
  #  build: ./flaskapp
  #  volumes:
  #    - .:/code
  #  ports:
  #    - "4000:4000"
  #  environment:
  #    - FLASK_ENV=development
  #  restart: always

  flaskapp:
      build: ./flaskapp
      expose:
        - "5000"
      volumes:
        - ./flaskapp:/code
      environment:
        - FLASK_ENV=development
        - DRF_HOST=djangoapp
        - DRF_PORT=5000
